pool:
  name: AzurePipelines-CI

trigger:
  - master
  - develop
  - feature/**

variables:
  RUN_ID: "0.0.0-ci-AzurePipelines-$(Build.SourceVersion)-$(Agent.OS)+$(Build.BuildNumber)"

jobs:
  - job: macOS
    pool:
      vmImage: "macOS-latest"
    steps:
      - script: |
          brew install flex bison
          brew install libmicrohttpd
        displayName: "Install Dependencies"

      - task: CMake@1
        inputs:
          cmakeArgs: "-S .. -B . -DCMAKE_BUILD_TYPE:STRING=Debug  -DRUN_ID=$(RUN_ID)"
        displayName: "CMake Configure"

      - task: CMake@1
        inputs:
          cmakeArgs: "--build . --target all -j 2 --verbose"
        displayName: "CMake Build"

      - script: |
          ctest --test-dir ./test
        displayName: "CMake Run Test"

  - job: Windows
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - task: CMake@1
        inputs:
          cmakeArgs: "-S .. -B . -DCMAKE_BUILD_TYPE:STRING=Debug -DRUN_ID=$(RUN_ID) -A x64"
        displayName: "CMake Configure"

      - task: MSBuild@1
        inputs:
          solution: 'build\ALL_BUILD.vcxproj'
          msbuildArchitecture: "x64"
          maximumCpuCount: true

      - script: |
          ctest --test-dir ./test
        displayName: "CMake Run Test"

  - job: Ubuntu
    pool:
      vmImage: ubuntu-latest

    steps:
      - checkout: self
      - script: |
          mkdir ./build
        displayName: "Install Dependencies"

      - task: CMake@1
        inputs:
          cmakeArgs: "-S .. -B . -DCMAKE_BUILD_TYPE:STRING=Debug -DRUN_ID=$(RUN_ID)"
        displayName: "CMake Configure"
      - task: CMake@1
        inputs:
          cmakeArgs: "--build . --target all -j 2 --verbose"
        displayName: "CMake Build"

      - script: |
          ctest --test-dir ./test
        displayName: "CMake Run Test"
